# Random Forest
É uma técnica que aplica diversas árvores de decisão e utiliza métodos de __Ensemble__ para combinar os resultados dessas árvores e obter uma predição única. Para problemas de __classificação__, o resultado será a moda (classe mais votada) entre as árvores. Para problemas de __regressão__, o resultado será a média das previsões das árvores.

__Funcionamento:__
- __Criação de várias árvores de decisão:__ Cada uma das árvores criadas é gerada a partir de um subconjunto aleatório de dados de treino. Esse processo é chamado de __bagging__, em que amostras aleatórias com reposição são extraídas dos dados de treino para formar o conjunto de dados que será usado por cada árvore. Além disso, o objetivo do __bagging__ é reduzir a variância, de forma a garantir que árvores diferentes não sejam treinadas com exatamente os mesmos dados.  
- __Seleção aleatória dos atributos:__ Em cada divisão de um nó, o algoritmo seleciona aleatoriamente um subconjunto de atributos ao invés de considerar todos os atributos para a divisão em cada nó da árvore. Isso é uma forma de garantir que cada árvore seja diferente, fazendo com que aumente a diversidade entre as árvores e evita que elas captem o mesmo padrão nos dados.
- __Treinamento das árvores:__ Cada árvore é treinada de maneira independente, e cada árvore se torna "especialista" em diferentes partes dos dados.
- __Agregação dos resultados:__ No caso de problemas de __classificação__, a Random Forest combina as previsões das diferentes árvores por meio de votação majoritária. Para __regressão__, a previsão final é a média das previsões de todas as árvores.

__Vantagens:__
- __Redução de Overfitting:__ Por utilizar diversas árvores e combinar suas previsões, tende a ser mais robusto e menos propenso a overfitting.
- __Lida com dados de alta dimensionalidade:__ Lida bem com grandes números de variáveis.
- __Estabilidade:__ Pequenas variações presentes nos dados não afetam muito seu desempenho.
- __Capacidade de lidar com dados ausentes:__ Consegue fazer seu treinamento mesmo com dados faltantes, pois substitui esses dados por estimativas durante o processo de treinamento.

__Desvantagens:__
- Possui alto custo computacional principalmente para grandes conjuntos de dados.
- Difícil de interpretar.

# Codificação

In [1]:
# Importação do google drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# Importações

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
import warnings
warnings.filterwarnings('ignore')
plt.style.use('ggplot')

from sklearn.model_selection import train_test_split, KFold, cross_val_score, GridSearchCV, RandomizedSearchCV
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier

In [3]:
alvo = pd.read_pickle('/content/drive/MyDrive/Udemy/ML com Python/1 - Aprendizado Supervisionado: Classificacao/heart.pkl')

# Variáveis previsoras onde as variáveis categóricas foram transformadas em numéricas manualmente, sem escalonamento
previsores = pd.read_pickle('/content/drive/MyDrive/Udemy/ML com Python/1 - Aprendizado Supervisionado: Classificacao/heart2.pkl')

# previsores_esc = pd.read_pickle('/content/drive/MyDrive/Udemy/ML com Python/1 - Aprendizado Supervisionado: Classificacao/heart3.pkl')

# Variáveis previsoras onde as variáveis categóricas foram transformadas em numéricas pelo LabelEncoder.
previsores2 = pd.read_pickle('/content/drive/MyDrive/Udemy/ML com Python/1 - Aprendizado Supervisionado: Classificacao/heart4.pkl')

# Variáveis previsoras onde as variáveis categóricas foram transformadas em numéricas pelo LabelEncoder e OneHotEncoder, sem escalonamento.
previsores3 = pd.read_pickle('/content/drive/MyDrive/Udemy/ML com Python/1 - Aprendizado Supervisionado: Classificacao/heart5.pkl')

# Variáveis previsoras onde as variáveis categóricas foram transformadas pelo LabelEncoder e OHE, com escalonamento.
previsores3_esc = pd.read_pickle('/content/drive/MyDrive/Udemy/ML com Python/1 - Aprendizado Supervisionado: Classificacao/heart6.pkl')

In [4]:
X_tr, X_ts, y_tr, y_ts = train_test_split(previsores, alvo, test_size=.3, random_state=0)

In [5]:
X_tr.shape, y_tr.shape

((641, 11), (641,))

In [6]:
X_tr.shape, y_tr.shape

((641, 11), (641,))

In [7]:
# Instanciar o modelo
rf = RandomForestClassifier(random_state=0)

# Ajuste do modelo aos dados de treino
rf.fit(X_tr, y_tr)

RandomForestClassifier(random_state=0)

In [8]:
# Realizar as predições
predict_rf = rf.predict(X_ts)
predict_rf

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1])

In [9]:
y_ts

306    1
710    0
298    1
466    0
253    0
      ..
49     1
456    1
342    1
906    1
116    1
Name: HeartDisease, Length: 276, dtype: int64

In [10]:
print(f'Acurácia: {accuracy_score(y_ts, predict_rf)*100:.2f}')

Acurácia: 85.51


In [11]:
confusion_matrix(y_ts, predict_rf)

array([[100,  21],
       [ 19, 136]])

In [12]:
print(classification_report(y_ts, predict_rf))

              precision    recall  f1-score   support

           0       0.84      0.83      0.83       121
           1       0.87      0.88      0.87       155

    accuracy                           0.86       276
   macro avg       0.85      0.85      0.85       276
weighted avg       0.85      0.86      0.85       276



In [13]:
# Verificação de overfitting

predict_rf_tr = rf.predict(X_tr)
print(f'Acurácia: {accuracy_score(y_tr, predict_rf_tr)*100:.2f}')

Acurácia: 100.00


In [14]:
confusion_matrix(y_tr, predict_rf_tr)

array([[289,   0],
       [  0, 352]])

# Validação Cruzada e Teste de Diferentes Parâmetros

In [15]:
# KFold
kfold = KFold(n_splits = 10, shuffle=True, random_state=0)

In [16]:
# Aplicação da validação cruzada
result_rf = cross_val_score(rf, X_tr, y_tr, cv=kfold)
print(f'Acurácia: {result_rf.mean()*100:.2f} Desvio Padrão: {result_rf.std()*100:.2f}')

Acurácia: 86.42 Desvio Padrão: 3.65


In [17]:
# Avaliação no conjunto de teste
print(f'Acurácia: {accuracy_score(y_ts, predict_rf)*100:.2f}')

Acurácia: 85.51


In [18]:
print(confusion_matrix(y_ts, predict_rf))

[[100  21]
 [ 19 136]]


In [19]:
print(classification_report(y_ts, predict_rf))

              precision    recall  f1-score   support

           0       0.84      0.83      0.83       121
           1       0.87      0.88      0.87       155

    accuracy                           0.86       276
   macro avg       0.85      0.85      0.85       276
weighted avg       0.85      0.86      0.85       276



In [20]:
# Diferentes parâmetros a testar

params = {
    'n_estimators': [50, 100, 150],
    'criterion': ['gini', 'entropy'],
    'max_depth': [3, 4, 5],
    'min_samples_split': [2, 3, 4, 5],
    'min_samples_leaf': [1, 2, 3, 4, 5]
}

In [21]:
grid_search = GridSearchCV(rf, param_grid=params, cv=kfold)

In [22]:
# Ajuste dos dados
grid_search.fit(X_tr, y_tr)

GridSearchCV(cv=KFold(n_splits=10, random_state=0, shuffle=True),
             estimator=RandomForestClassifier(random_state=0),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [3, 4, 5],
                         'min_samples_leaf': [1, 2, 3, 4, 5],
                         'min_samples_split': [2, 3, 4, 5],
                         'n_estimators': [50, 100, 150]})

In [23]:
# Verificação dos melhores parâmetros
print(f'Melhores parâmetros: {grid_search.best_params_}')
print(f'Melhor acurácia: {grid_search.best_score_}')

Melhores parâmetros: {'criterion': 'gini', 'max_depth': 5, 'min_samples_leaf': 3, 'min_samples_split': 2, 'n_estimators': 50}
Melhor acurácia: 0.8611057692307693


# Aplicação dos melhores parâmtros aos dados de teste

In [24]:
best_rf = RandomForestClassifier(
    n_estimators=50,
    criterion='gini',
    max_depth=5,
    min_samples_split=2,
    min_samples_leaf=3,
    random_state=0
)

In [25]:
best_rf.fit(X_tr, y_tr)

RandomForestClassifier(max_depth=5, min_samples_leaf=3, n_estimators=50,
                       random_state=0)

In [26]:
# Realizar as predições
predict_best_rf = best_rf.predict(X_ts)
predict_best_rf

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1])

In [27]:
print(f'Acurácia: {accuracy_score(y_ts, predict_best_rf)*100:.2f}')

Acurácia: 85.14


In [28]:
confusion_matrix(y_ts, predict_best_rf)

array([[102,  19],
       [ 22, 133]])

In [29]:
print(classification_report(y_ts, predict_best_rf))

              precision    recall  f1-score   support

           0       0.82      0.84      0.83       121
           1       0.88      0.86      0.87       155

    accuracy                           0.85       276
   macro avg       0.85      0.85      0.85       276
weighted avg       0.85      0.85      0.85       276



In [30]:
# Verificação de overfitting

predict_best_rf_tr = best_rf.predict(X_tr)
print(f'Acurácia: {accuracy_score(y_tr, predict_best_rf_tr)*100:.2f}')

Acurácia: 90.33


In [31]:
confusion_matrix(y_tr, predict_best_rf_tr)

array([[249,  40],
       [ 22, 330]])